export {default as NavBar} from "./nav-bar/NavBar.jsx"
export {default as Ad} from "./ad-container/Ad.jsx"
export {default as Button} from "./button/Button.jsx"
export {default as IconCard} from "./icon-card/IconCard.jsx"
export {default as Footer} from "./footer/Footer.jsx"